#!/command/with-contenv sh

/bin/sleep 4
/bin/echo "[NOTICE] Watching for certificate renewals from certbot for ${HOSTNAME}"
MD5SUM=$(md5sum "/etc/letsencrypt/live/${HOSTNAME}/fullchain.pem" | cut -d " " -f1)
/bin/echo "[DEBUG ] /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem (found) $MD5SUM"
while true; do
    if [[ $MD5SUM != $(md5sum "/etc/letsencrypt/live/${HOSTNAME}/fullchain.pem" | cut -d " " -f1) ]]; then
        /bin/echo "[NOTICE] Found new certificate for ${HOSTNAME}, restarting dovecot."
        /bin/echo "[INFO  ] /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem (updated) $MD5SUM"
        /bin/cat /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem | /usr/bin/openssl x509 -noout -subject -dates
        /bin/cp /etc/letsencrypt/live/${HOSTNAME}/privkey.pem /etc/ssl/key.pem
        /bin/cp /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem /etc/ssl/certificate.pem
        /bin/s6-svc -r /run/s6/services/30-dovecot
        MD5SUM=$(md5sum "/etc/letsencrypt/live/${HOSTNAME}/fullchain.pem" | cut -d " " -f1)
        if [ ! -z "${SLACK_URL_FILE}" ]; then
            SLACK_URL=$(/bin/cat ${SLACK_URL_FILE})
            MESSAGE="{\"attachments\":[{\"color\":\"#36a64f\",\"text\":\":closed_lock_with_key: Found new certificate for ${HOSTNAME}\"}]}"
            curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" "${SLACK_URL}" > /dev/null 2>&1
        fi
    fi
    /bin/sleep 1h
done
