services:
  server:
    build: .
    hostname: mailserver
    depends_on:
      - bootloader
    ports:
      - target: 25
        published: 25
        protocol: tcp
        mode: host
      - target: 993
        published: 993
        protocol: tcp
        mode: host
      - target: 995
        published: 995
        protocol: tcp
        mode: host
    environment:
      - "HOSTNAME=mail.contoso.com"
      - "DOMAIN=contoso.com"
      - "DEVNULL=sales@contoso.com webmaster@contoso.com"
      - "ALIASES=contoso.local"
      - "TIMEZONE=America/New_York"
      - "PASSWORD_FILE=/etc/letsencrypt/live/password.txt"
      - "SLACK_URL_FILE=/run/secrets/slack-webhook"
    command: >
      /bin/sh -c "
        trap exit TERM;
        /usr/sbin/postconf -X smtpd_sender_restrictions;
        echo 'smtpd_forbid_unauth_pipelining = no' >> /etc/postfix/main.cf;
        netstat -tulnp;
        sleep 120 & wait $${!};
      "
    volumes:
      - storage:/var/mail
      - certificates:/etc/letsencrypt/live/

  bootloader:
    build:
      context: ./test
      dockerfile: Dockerfile.openssl
    hostname: bootloader
    environment:
      - "TZ=America/New_York"
    entrypoint: >
      /bin/sh -c "(
        trap exit TERM;
        mkdir /etc/letsencrypt/live/mail.contoso.com;
        echo 'hunter2' > /etc/letsencrypt/live/password.txt;
        openssl req -x509 -sha256 -nodes -newkey rsa:4096 -keyout /etc/letsencrypt/live/mail.contoso.com/privkey.pem -out /etc/letsencrypt/live/mail.contoso.com/fullchain.pem -days 7200 -subj '/CN=self.signed/';
        sleep 120 & wait $${!};
        exit 99;
      )"
    volumes:
      - certificates:/etc/letsencrypt/live/

  sut:
    build:
      context: ./test
      dockerfile: Dockerfile.openssl
    hostname: sut
    depends_on:
      - server
    environment:
      - "TZ=America/New_York"
    entrypoint: /entrypoint.sh
    volumes:
      - certificates:/etc/letsencrypt/live/

volumes:
  storage:
  certificates:
