Socket                  inet:8891@localhost
Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes
Canonicalization        relaxed/relaxed
Mode                    sv
SubDomains              no
AutoRestart             yes
AutoRestartRate         10/1M
Background              no
DNSTimeout              5
SignatureAlgorithm      rsa-sha256
UserID                  opendkim
UMask                   007
PidFile                 /run/opendkim/opendkim.pid
KeyTable                /etc/opendkim/keytable
SigningTable            refile:/etc/opendkim/signingtable
InternalHosts           127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, ::1
