#!/command/with-contenv sh

chown catchall:catchall /var/mail

while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.db ]; do
    test -f /etc/postfix/virtual || ( /bin/echo "[WARN  ] /etc/postfix/virtual not found" )
    test -f /etc/postfix/virtual.db || ( /bin/echo "[WARN  ] /etc/postfix/virtual.db not found" )
    echo "[INFO  ] postfix waiting for configuration initialization ..."
    sleep 2
done

install -Dm644 /etc/resolv.conf /var/spool/postfix/etc/resolv.conf
install -Dm644 /etc/hosts       /var/spool/postfix/etc/hosts
install -Dm644 /etc/nsswitch.conf /var/spool/postfix/etc/nsswitch.conf

echo "[NOTICE] Starting postfix"
exec /usr/sbin/postfix start-fg
