#!/command/with-contenv sh

chown catchall:catchall /var/mail

while [ ! -f /etc/postfix/virtual ] || [ ! -f /etc/postfix/virtual.lmdb ]; do
    test -f /etc/postfix/virtual || ( /bin/echo "[WARN  ] /etc/postfix/virtual not found" )
    test -f /etc/postfix/virtual.lmdb || ( /bin/echo "[WARN  ] /etc/postfix/virtual.lmdb not found" )
    echo "[INFO  ] postfix waiting for configuration initialization ..."
    sleep 2
done

echo "[NOTICE] Starting postfix"
exec /usr/sbin/postfix start-fg
