#!/usr/bin/with-contenv sh
/bin/sleep 4
echo "[*] Watching for certbot renewals"
while true; do
    if [ -f /etc/letsencrypt/live/${HOSTNAME}/.deploy ]; then
        /bin/echo "Found new certificate for ${HOSTNAME}, restarting dovecot."
        /bin/cat /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem | /usr/bin/openssl x509 -noout -subject -dates
        /bin/cp /etc/letsencrypt/live/mail.ozmonet.com/privkey.pem /etc/ssl/key.pem
        /bin/cp /etc/letsencrypt/live/mail.ozmonet.com/fullchain.pem /etc/ssl/certificate.pem
        /bin/s6-svc -r /run/s6/services/30-dovecot
        /bin/rm /etc/letsencrypt/live/${HOSTNAME}/.deploy
    fi
    /bin/sleep 1h
done
