#!/usr/bin/with-contenv sh

if [ -f /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem ]; then
    echo "Using /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem"
    cp /etc/letsencrypt/live/${HOSTNAME}/fullchain.pem /etc/ssl/certificate.pem
fi

if [ -f /etc/letsencrypt/live/${HOSTNAME}/privkey.pem ]; then
    echo "Using /etc/letsencrypt/live/${HOSTNAME}/privkey.pem"
    cp /etc/letsencrypt/live/${HOSTNAME}/privkey.pem /etc/ssl/key.pem
fi

test -f /etc/ssl/certificate.pem || exit 1
test -f /etc/ssl/key.pem || exit 1
