#!/usr/bin/with-contenv sh

/usr/sbin/postconf "myhostname=${HOSTNAME:=mail.contoso.localdomain}"
/usr/sbin/postconf "mydomain=${DOMAIN:=contoso.localdomain}"
/usr/sbin/postconf "virtual_alias_domains=${ALIASES:=fabrikam.localdomain}"

/bin/echo "@${DOMAIN}        catchall" >> /etc/postfix/virtual
for d in $ALIASES; do
    /bin/echo "@${d}        catchall" >> /etc/postfix/virtual
done

/bin/cat /etc/postfix/virtual

/usr/sbin/postmap /etc/postfix/virtual
/usr/sbin/postalias /etc/postfix/aliases
